### ISSUE TITLE
Server error generated when getFileInfo returns no data

### ISSUE THREAD

**Issue by arifje** [nystudio107/craft3-transcoder#10]
When ffprobe can't run for some reason or there's no valid file data returned, getFileInfo() generates an server error which is not catched correctly:

![screenshot 2018-10-26 at 09 40 28](https://user-images.githubusercontent.com/1286410/47551765-5f315d00-d903-11e8-9078-0000f2fe1131.png)

Edit: for now I resolved it with:

```
{% set videoData = (craft.transcoder.getFileInfo(video, true)) ? craft.transcoder.getFileInfo(video, true) : false %}
```
But I don't know if this is the best way.

**Comment by khalwat** [comment]
Fixed in https://github.com/nystudio107/craft-transcoder/commit/af102a1d1d134cadf64c01daf15a494262d124aa
