### ISSUE TITLE
How to prevent encoded files are deleted when clearing cache?

### ISSUE THREAD

**Issue by arifje** [nystudio107/craft3-transcoder#12]
While developing our new website I noticed encoded videos where missing after a while, but I didn't understand why. Turns out that clearing the cache also deletes ALL encoded files (images/videos). 

How can I prevent these files are getting deleted? In our case it's - very - important that these files stay alive. We can't take the risk that a admin clears all cache and forgets to uncheck transcoder files manually...

Thanks!

**Comment by khalwat** [comment]
Yeah that's by design, which arguably is not good for your use-case. I see your PR addresses it, though I think a better way might be just to never show that Clear Caches option rather than having it be there, but do nothing.

**Comment by khalwat** [comment]
I changed the PR somewhat; I had to add the settings model properties and validators, but also the `clearCaches` setting now just determines whether or not the Clear Caches is registered. If off, it won't appear in the CLI or in the CP to begin with.

https://github.com/nystudio107/craft-transcoder/commit/58ce0135946e386815244c03dc0c4783907c455d
