### ISSUE TITLE
How to: prevent new encoding after parameters/preferences change (bitrate)

### ISSUE THREAD

**Issue by arifje** [nystudio107/craft3-transcoder#14]
As it appears, the filenames of the encoded videos are based on the SUFFIX_MAP parameters, which contains parameters like bitrate, height, width etc. In our case this is far from ideal, because when you change the bitrate, it won't match any of the encoded videos anymore and it has to be encoded again.

I'll try to explain why this is bad for us; we upload  15-20 videos on a daily base. We have thousands of videos. If we make a change to the bitrate preferences we don't want to loose all encoded videos, nor do we want to encode all these (thousands) of videos again. We just want to encode new videos we upload according to these new preferences. Videos that are already encoded should be preserved and not encoded again.

Is it possible to realise this?

**Comment by arifje** [comment]
Hi, is this something we can get fixed? We can make a budget available if required, but we really need to get this fixed. Thanks in advance.

**Comment by khalwat** [comment]
So the entire point is that each video that is generated with different settings will then have a different file name, based on the parameters that are used to create it. This mirrors how image transforms are done/named in Craft.

Your use-case is one where you'd probably need to either re-encode all the files, or rename all of the files.

But the way it works is currently on purpose. If you want to file a FR to alter how files are named, that sounds reasonable.
