### ISSUE TITLE
Undefined index: subtitle

### ISSUE THREAD

**Issue by arifje** [nystudio107/craft3-transcoder#17]
Random video upload caused this error, probably got something to do with the encoding type/meta data;

<img width="1090" alt="screenshot 2019-02-11 at 12 18 26" src="https://user-images.githubusercontent.com/1286410/52560139-9e72b380-2df7-11e9-9383-095c5fd6ac6f.png">

**Comment by khalwat** [comment]
This is fixed in https://github.com/nystudio107/craft-transcoder/commit/0e241eb9045bb0bc106513e276c5e606a95c0253 as well
