### ISSUE TITLE
Nothing Works (transVideoUrl, "auto-generated" video thumbnails, progress URLs, etc.)

### ISSUE THREAD

**Issue by kevincarpdev** [nystudio107/craft3-transcoder#18]
Hello,

I followed the installation instructions for the server installation, paid for the plugin, and copied the syntax exactly, however, I cannot get ANYTHING to work.

My syntax is as follows:

`{% for video in block.file_asset %}
    <video id="presentation1" class="video-js vjs-default-skin vjs-big-play-centered" controls preload="auto" data-setup="">
        {% set videoOptions = {
        "videoFrameRate": 60,
        "videoBitRate": "1000k",
        "width": 1000,
        "height": 800,
        "aspectRatio": "none",
        } %}
        {% set transVideoUrl = craft.transcoder.getVideoUrl(video, videoOptions) %}
        {% set progressUrl = craft.transcoder.getVideoProgressUrl(video, videoOptions) %}
        <source src="{{ transVideoUrl }}" type='video/mp4'>
    </video>
<h4>Progress URL: {{ progressUrl }}</h4>
{% endfor %}`

The videos are stored in an S3 volume, and i can get the links to work regular just fine by using `{{ video.getUrl() }}` so I know the assets are working. The thumbnails in the asset manager are also not showing up, as described as an automatic process in the plugin description...

The Craft installation is on Ubuntu 18-04 running PHP 7.1 and managed through Server Pilot.
This is for a high-end video production company, so this feature is very important. The source videos are already in .MP4 format, but eventually will need to convert .MOV files into .MP4 if this plugin truly does work.

Any suggestions? Where do I go from here?

**Comment by kevincarpdev** [comment]
Looks like thumbnails are only generated if uploaded through the Craft asset manager, and this seems to work sparingly at best. This does not work with assets uploaded through S3.

**Comment by kevincarpdev** [comment]
I have also tried using the getFileInfo function, and no matter what i pass it (an asset object, a hard-coded URL of an asset on an S3 URL, etc.) it returns an error:

"Return value of nystudio107\transcoder\services\Transcode::getFileInfo() must be of the type array, string returned"

` {% set fileInfo = craft.transcoder.getFileInfo(asset, true) %}
                <h5>{{ fileInfo }}</h5>`

Very frustrating that none of the features work in this plugin!

**Comment by khalwat** [comment]
@TheDictator sorry I am late getting back to you on this.

You mention initially that you cannot get _anything_ to work. Is this still the case? Have you verified that `ffmpeg` is properly installed and set up?

The plugin definitely works, I'm using it on several sites, and other people are as well. So it's likely either a config/setup issue, or perhaps you've run into some kind of bug/edge case that I'm not aware of.

**Comment by khalwat** [comment]
Do you have time to do a video share to try to work it out?

**Comment by kevincarpdev** [comment]
@khalwat - The only thing that works is the thumbnail generation when assets are uploaded through the Craft Asset Manager.

I could not get the transcoder URLs, or progress URLS to work either. 

`ffmpeg` is installed on the server correctly so I am not sure what the deal is.

I can do a video share this week if you have time, however I am on Indochina Time. Can you message me a time / day that works and we can make it happen? 

Thanks for your help!

**Comment by khalwat** [comment]
Are you able to use `ffmpeg` manually?

I'm available any time this week, let me know what would work for you.

**Comment by kevincarpdev** [comment]
Gahhh sorry i am just now seeing this. 

Can you email me @ carpenter.kevin@gmail.com and we can set up a time to do a screenshare in the next few days? 

I am still having trouble getting anything to work and I can run ffmpeg manually by doing `ffmpeg -version` and `ffmpeg`.

Mainly trying to get the `getFileInfo` function to work on an S3 asset by doing `{% set fileInfo = craft.transcoder.getFileInfo(asset.getUrl(), true) %}`

But I simply get an error message (`Invalid argument supplied for foreach()`). I have also just tried to pass it the asset object with no luck.

**Comment by helleholmsen** [comment]
@khalwat @TheDictator did you solve this? I'm experiencing the exact same problem. Nothing works :( I'm hosting my assets on S3, the plugin is installed and paid for, and ffmpeg is installed locally at `/usr/local/bin/ffmpeg`

**Comment by khalwat** [comment]
@helleholmsen Can you open a new issue, and we can diagnose your issue there?

Include any relative `storage/logs/web.log` information
