### ISSUE TITLE
Doesn't work :(

### ISSUE THREAD

**Issue by helleholmsen** [nystudio107/craft3-transcoder#29]
Nothing works :( Testing this locally. I'm hosting my assets on S3, the plugin is installed and paid for, and ffmpeg is installed at /usr/local/bin/ffmpeg. The error messages varies a bit, either it just outputs "unkown" when I'm trying to transform a video, or 

```
  {% set fileInfo = craft.transcoder.getFileInfo(video, true) %}
  <h4>{{ fileInfo }}</h4>
```

gives me _"Array to string conversion"_ (sometimes). Am I missing something?

**Comment by khalwat** [comment]
So please ensure that `devMode` is on, and then check `storage/logs/web.log` and search on `transcoder` to see if you can find any error or status messages

**Comment by helleholmsen** [comment]
@khalwat no error messages. All I can find is 

`[ma5u1vne35q1c5qvgcuv95ng4f][info][nystudio107\transcoder\Transcoder::init] Transcoder plugin loaded`

**Comment by khalwat** [comment]
You should have a whole lot more than that. Try this:

- Delete all of the log files on `storage/logs/`
- Make the problem happen by reloading the page or whatever

Then send me the complete `web.log` file to: andrew@nystudio107.com

**Comment by helleholmsen** [comment]
@khalwat thanks! I sent you an email:)

**Comment by khalwat** [comment]
Ended up being an incomplete local software install -- `ffprobe` was missing from the `brew` install
