### ISSUE TITLE
timeInSecs of 20 seems to be the only value that works

### ISSUE THREAD

**Issue by tyssen** [nystudio107/craft3-transcoder#46]
### Question
I'm testing Transcoder on a page that has five videos with 

		{% set transVideoThumbUrl = craft.transcoder.getVideoThumbnailUrl(videoURL, {
		    "width": 550,
		    "height": 367,
		    "timeInSecs": 20,
		})%}

Only two of the five videos were showing images and I found that some are less than 20 seconds in length. But if I change `timeInSecs` to anything other than 20, I get no thumbnails for any of the videos.

I've tried values from 1 up to 30, but 20 is the only one that works. Not sure how to proceed in terms of troubleshooting this issue.

**Comment by khalwat** [comment]
Any number should work, that's just passed in as the `-ss` parameter to ffmpeg:

https://github.com/nystudio107/craft-transcoder/blob/v1/src/services/Transcode.php#L264

https://trac.ffmpeg.org/wiki/Seeking

**Comment by tyssen** [comment]
Sorry for wasting your time. They're there now. :/
