### ISSUE TITLE
Feature request; seperate path & url configuration for thumbnails

### ISSUE THREAD

**Issue by arifje** [nystudio107/craft3-transcoder#5]
Currently both images and videos are stored in the video location. Would be better if we could split up these types of content: a seperate path/url for thumbnails and videos, defined in the config.

Thanks!

**Comment by khalwat** [comment]
Another good idea. Will do.

**Comment by khalwat** [comment]
This is implemented in 1.2.0 (thanks for the PR!) https://github.com/nystudio107/craft-transcoder/releases/tag/1.2.0
