### ISSUE TITLE
Videos not loading

### ISSUE THREAD

**Issue by Jordenjj** [nystudio107/craft3-transcoder#56]
### Question
Hello,
My videos do not seem to be transcoding. The progress url outputs this.
`,"duration":"unknown","time":0,"progress":"unknown","message":"encoding GIF, can't determine duration"}`

What can cause this? It seems like the transcoding isn't starting at all. ffmpeg has been installed via Plesk. The log file shows nothing strange on first glance

Thank you,

**Comment by khalwat** [comment]
What version of the plugin are you using?

Have you checked your `web.log` to see if there are any errors?

**Comment by Jordenjj** [comment]
Latest, just got it today. Log shows no errors.

**Comment by khalwat** [comment]
You state that `ffmpeg` is installed via Plesk. What is the path to that executable on the file system, and does that match what is in your `config/transcoder.php` file? <https://github.com/nystudio107/craft-transcoder/blob/develop/src/config.php#L29>

**Comment by Jordenjj** [comment]
Excuse my late response.
My general config PHP file does not seem to include anything on transcoder. Therefore I can't copy anything over. What could cause this? Could you maybe share what needs to be in transcoder.php?

Edit: I found my mistake regarding the above. Will report back after checking.

**Comment by Jordenjj** [comment]
Alright, paths in transcoder.php file are now:

    // The path to the ffmpeg binary
    'ffmpegPath' => '/vendor/php-ffmpeg/php-ffmpeg/src/FFMpeg.php',

    // The path to the ffprobe binary
    'ffprobePath' => '/vendor/php-ffmpeg/php-ffmpeg/src/FFProbe.php',

**Comment by zawilliams** [comment]
@Jordenjj you need to provide a path to the binaries, not the PHP library. If you run `which ffmpeg` and `which ffprobe` on the command line, you will be able to find where the binary is located. You can copy and paste that into the value for `ffmpegPath` and `ffprobePath`.

**Comment by khalwat** [comment]
What @zawilliams said... you need to point to the actual installed binaries, not `php-ffmpeg`.

Just to be clear... you put this in your `config/transcoder.php` file and not your `general.php` file.

**Comment by Jordenjj** [comment]
I've been trying to get ffmpeg installed right with plesk and centos7 but I can't seem to do it. Every installer fails because of no sudo access on shared hosting. This might be a 'me' problem. 
Is refunding possible when I am to blame?

Thank you.

**Comment by khalwat** [comment]
@Jordenjj should be -- but Pixel & Tonic handles all aspects of plugin sales/refunds, etc. Email them at: support@CraftCMS.com and point them to this thread.
