### ISSUE TITLE
Craft 5 Support

### ISSUE THREAD

**Issue by andypullen** [nystudio107/craft3-transcoder#73]
Do you have plans for updating this plugin for Craft 5? Thanks!

**Comment by khalwat** [comment]
Yep, it's coming!

**Comment by zawilliams** [comment]
Is it coming soon?

**Comment by khalwat** [comment]
Yessir!

**Comment by urbantrout** [comment]
Looking forward to it! :)

**Comment by arifje** [comment]
Same here!

**Comment by andypullen** [comment]
@khalwat Do you happen to have a rough timeline? Thanks!

**Comment by GeraldSandel** [comment]
Yes same here waiting on it!

**Comment by khalwat** [comment]
It's pretty much done; just need to do a little QA and cleanup, and away we go.

**Comment by khalwat** [comment]
Released for Craft 5 -> https://github.com/nystudio107/craft-transcoder/releases/tag/5.0.0

**Comment by urbantrout** [comment]
Awesome, thanks!
