### ISSUE TITLE
How to access transcoder on API level

### ISSUE THREAD

**Issue by arifje** [nystudio107/craft3-transcoder#8]
Not a bug, but more a request for example; I want to access the Transcoder methods from another plugin (Elements API) and I don't know how.

I tried to access services:

```
$transcoderService = \nystudio107\transcoder\Transcoder::$plugin->getInstance();
$transcoderService->Transcode->getVideoUrl();
```

But no luck.

Thanks in advance!

**Comment by khalwat** [comment]
You'd do something like this:

```
use nystudio107\transcoder\Transcoder;

$url = Transcoder::$plugin->transcode->getVideoUrl($filePath, $videoOptions);


```
